### ISSUE TITLE
Sponsorship tweaks 

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/frontend#103]
We made some changes to the packages: added “tech talk” to silver and added “mention in pre-event emails” for gold. https://docs.google.com/document/d/1OYV_bW2Vn_kjtkzKgfHM0KfxXm-zhTRWE2RjeouLuxU/edit?usp=sharing
Also, add some statistics: gender, diversity, age, and attendance.

**Comment by dhruvilp** [comment]
Already done!! Check it out (branch: sponsorship)

**Comment by thekabistro** [comment]
Closing... This will move to the Sponsorship project.
