### ISSUE TITLE
Recreate the /live site

### ISSUE THREAD

**Issue by thekabistro** [HackRU/frontend#136]
For the day of, this is the core of the dashboard last semester, without the login.

So it should include the same announcements, upcoming events and the common links.

It should be at hackru.org/live

**Comment by shivanmodha** [comment]
I'll add a dummy endpoint to `react-router` to get this started

**Comment by thekabistro** [comment]
This is _very_ low priority.  Like don't worry about this for a while.

**Comment by ryanisaacg** [comment]
We'll probably have to add more stuff day-of but right now we have a pretty nice looking live site.
