### ISSUE TITLE
Form Fields should be mandatory

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/frontend#15]
We had too many blank responses last HackRU... so if they're empty, force the user to fill them.

We don't force users to update fields though, preferably.

**Comment by TresTres** [comment]
The question is when exactly would we'd be forcing to fill them.  Updates to the user in LCS are triggered upon logging out or saving; there is no formal final submission process.  The back-end has no knowledge if the submitted information is finalized for consideration or not.  

What I can do thanks to LCS:  Upon an update, I could trigger a check for filled fields and then `$set` `finalized` and `missing_fields` attributes.  We will need to figure out a way to make this known cosmetically.

**Comment by TresTres** [comment]
We are looking at this as part of #41, and there is an existing alert system in place notifying users if there are unfinished fields.  

It should be made more robust though.
