### ISSUE TITLE
Keep checkboxes checked after a reload

### ISSUE THREAD

**Issue by ryanisaacg** [HackRU/frontend#151]

**Comment by hemangandhi** [comment]
You might just want to get rid of them if the user's registration status is not `unregistered`. That's what we used to do.

**Comment by shivanmodha** [comment]
## `UserProfileForm` overview
Now with two "views"
- Overview, showing what you put in
    - ![image](https://user-images.githubusercontent.com/29020430/51080822-800e8080-16b0-11e9-838f-2d64ca2ade36.png)
- Edit view, with all fields editable
    - ![image](https://user-images.githubusercontent.com/29020430/51080864-5144da00-16b1-11e9-91ee-39956e119a77.png)

In overview, if you have submitted the form, there shouldn't be confusion that you haven't checked the buttons. In edit view, the first checkbox is linked to the registration status. If the user already submitted the form once, it will already be checked. I am still under the belief that if you change your information, you need to reauthorize us to share your information, so for now that is not linked.

**Comment by hemangandhi** [comment]
Please link it.

If you read the policy, it allows the data to be used for whatever. So it's a bit misleading to let them check it again. 

Also unchecking the first box is nonsense, so please don't let it even show.

**Comment by shivanmodha** [comment]
both checkboxes linked

**Comment by hemangandhi** [comment]
Thank you.

Let me know if unchecking them tries to re-set the user `registration_status` - those transitions would need a quick backend tweak.

**Comment by shivanmodha** [comment]
it doesn't
