### ISSUE TITLE
Incomplete Form Update Feedback

### ISSUE THREAD

**Issue by thekabistro** [HackRU/frontend#158]
On pressing update if you have not filled out fields, it's not immediately obvious that the form has fields that need to be filled out.  It would be great if that incomplete field could grab focus and a message near the bottom by the update button to inform you that your form is incomplete.  I thought the button didn't work for a minute.

**Comment by shivanmodha** [comment]
![image](https://user-images.githubusercontent.com/29020430/51159031-0c59a880-1855-11e9-932c-085c42320647.png)

If i understand correctly?

**Comment by thekabistro** [comment]
Yes -- but fix that sentence?  "Some fields *are* invalid"?
