### ISSUE TITLE
Form: Non-options do not show up

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/frontend#16]
The library used [react-select](https://github.com/JedWatson/react-select) to make the autocompleting form is a bit broken: if a user puts in a custom value (when allowed) and then returns to the site, the custom value disappears.

**Comment by TresTres** [comment]
This has been taken care of in some extent by https://github.com/HackRU/frontend/commit/29f5883b0602a096ac0fc9a70174b92283aeea45
