### ISSUE TITLE
Dietary Restriction and Special Needs fields unclear

### ISSUE THREAD

**Issue by no-vac** [HackRU/frontend#163]
It is unclear whether leaving the Dietary Restrictions and Special Needs fields in the profile empty resulting in "unanswered" is same as NONE or if it results in a hold on the application

**Comment by ryanisaacg** [comment]
If the form submits with no errors, there is no hold on the application. This should be clear from the "Application Status" on the dashboard page. If you feel this is still an issue, feel to reopen with more detail.

Thanks!
