### ISSUE TITLE
Admin Dashboard: Update waves

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/frontend#17]
We want to allow for directors to update the "wave" it is in registration (so the first `n` accepted hackers from wave `k` get an acceptence email welcoming them and lets them confirm attendence and those who said they were coming in wave `k-1` are considered RSVPed).

I'll link the docs from the backend as I make them. This should be in the admin dashboard.

**Comment by hemangandhi** [comment]
Also, there'll be a thing with email templates, so that the judges can be emailed through the dashabord too.

**Comment by hemangandhi** [comment]
https://github.com/HackRU/lcs/wiki/LCS-API-Endpoints#send-emails <- this is one of the critical endpoints for this, so that you can email the people whose statuses have changed.

The other useful endpoint is the update one: https://github.com/HackRU/lcs/wiki/LCS-API-Endpoints#update so that user statuses are updated.

**Comment by thekabistro** [comment]
Closing. This issue is more relevant to the VHX Scheduler project and no longer recommend for implementation.
