### ISSUE TITLE
Confirming Attendence

### ISSUE THREAD

**Issue by thekabistro** [HackRU/frontend#181]
It appears that some folks who went to press the "confirm" attendance button did not have their status change.  Needs further investigating.

**Comment by hemangandhi** [comment]
If this is based on particular emails, look at the timestamps on their tokens... the one email we got can't have possibly confirmed within 72 hours of the email they got.

**Comment by thekabistro** [comment]
We've heard about at least 3.

**Comment by shivanmodha** [comment]
Does this issue still exist?

**Comment by ryanisaacg** [comment]
At the latest meeting we discussed and the numbers don't show any issue, so we'll close for now
