### ISSUE TITLE
Admin Panel / VHX Scheduler Rework 

### ISSUE THREAD

**Issue by thekabistro** [HackRU/frontend#194]
Creating this to make sure we remember to create this functionality.  

We (admins) need the ability to 
- promote / demote the role for scanning QR codes to LCS accounts
- send out magic links for directors, organizers and volunteers (maybe sponsors too).

The VHX Scheduler used to handle this, but we're largely decommissioning that separate tool and integrating

**Comment by shivanmodha** [comment]
Does the LCS endpoints already exist? I can take this up if the backend functionality already exists
