### ISSUE TITLE
Animations 

### ISSUE THREAD

**Issue by thekabistro** [HackRU/frontend#240]
Numbers can go from 0 - number (on sponsorship & splash pages)
Icons on background can bounce & spin and stuff (see the #f19 assets channel for what marketing has been making)

**Comment by shivanmodha** [comment]
Done as of #212

**Comment by thekabistro** [comment]
- Icon bouncing completed with #274 !  
- Numbers animation still in the pipeline

**Comment by shivanmodha** [comment]
@ryanmao725 Wanna try this out in your free time :) Very low priority tho
