### ISSUE TITLE
LCS Serverless Changes

### ISSUE THREAD

**Issue by shivanmodha** [HackRU/frontend#271]
Ticket to track LCS serverless changes that require changes to the Frontend.

**Comment by shivanmodha** [comment]
@Kironb deployed LCS changes here: https://b59jg8tkn9.execute-api.us-east-1.amazonaws.com/dev

**Comment by mjrb** [comment]
@ryanmao725 I'm going to repoint cloudfront tomorrow which will cut over API.hackru.org to this new version. This includes both dev and prod. If I can get verification that nothing looks broken with the above base url I would feel slightly better, but we need to push this along

**Comment by ryanmao725** [comment]
@Kironb There seems to be an issue with the new url. I get the error message "Unable to import module 'authorize'" when attempting to login/signup.

**Comment by shivanmodha** [comment]
Will keep this open until we can confirm that that the resume endpoint is still functional; however, as of yet, we don't know if its related to the serverless changes.
