### ISSUE TITLE
Schedule UX

### ISSUE THREAD

**Issue by thekabistro** [HackRU/frontend#277]
- [x] The HackRU logo needs to move higher up on the screen when in mobile view.  Or there need to be some assets there
![image](https://user-images.githubusercontent.com/5863372/74614501-59f2b580-50e6-11ea-8f1c-bcc79ce720c2.png)
- [ ] Create a visual divide on desktop between the Saturday and Sunday events.  Looks weird to have the headers showing up twice. 
![image](https://user-images.githubusercontent.com/5863372/74614562-c968a500-50e6-11ea-9f08-8299ee5243ef.png)
- [x] Forgot Password / Sign up / Login visual discrepancies covered in #276

**Comment by shivanmodha** [comment]
![image](https://user-images.githubusercontent.com/29020430/74876297-6880dd00-5331-11ea-94ea-7f9dd44a2f32.png)
This is spelled wrong too, was an issue that slipped by last semester unfortunately

**Comment by shivanmodha** [comment]
Schedule changes are incoming from day of, so its not a priority. @ryanmao725 what if we moved to a calendar component instead of a table that reads from our calendar?

**Comment by shivanmodha** [comment]
Completed for fall 2020
