### ISSUE TITLE
Local Storage Caching

### ISSUE THREAD

**Issue by thekabistro** [HackRU/frontend#278]
- It would appear that some folks have the old style sheet cached.  They're getting an odd mix of new assets with old styles.  This needs to be investigated further! 

![image](https://user-images.githubusercontent.com/5863372/74614637-91ae2d00-50e7-11ea-8bc0-df58190f0590.png)

**Comment by shivanmodha** [comment]
We pushed out a preliminary fix to this by changing the name of the index file to `index-s20.css`. Seems to be working, but we need to think of a more permanent solution.

**Comment by shivanmodha** [comment]
This is a non issue for this next hackathon since we haven't changed the CSS file much, but this still needs to be investigated. We need a better way to handle this.

**Comment by shivanmodha** [comment]
This is a non-issue with material-ui
