### ISSUE TITLE
Why are you coming? New Registration form field

### ISSUE THREAD

**Issue by mjrb** [HackRU/frontend#279]
Add a multi select for common reasons for attending hackru. It should say most important reason first so that the array output has the array ranked in the user object. The field in the user object should be `reasons_coming`. If you want a list of common reasons I can try to come up one.

**Comment by shivanmodha** [comment]
@ryanmao725 Can we get this in before the soft release tomorrow?

**Comment by shivanmodha** [comment]
Completed!
