### ISSUE TITLE
HackRU logo flashes after animation completes

### ISSUE THREAD

**Issue by emilywritescode** [HackRU/frontend#288]
See video in the #tech-support channel

Google Chrome, Windows Surface
(Thanks Kaushal for reporting this issue)

**Comment by shivanmodha** [comment]
Appears to happen in Edge too, maybe an antialiasing issue? It seems related to SVG motion path animations trigger a repaint.

**Comment by shivanmodha** [comment]
@emilywritescode do you remember if this was an issue last semester too? We are using the same animation filter, just changed the asset

**Comment by emilywritescode** [comment]
@shivanmodha Don’t remember this happening last semester. Also, I do not see this issue on either my iPhone or MacBook. Haven’t personally tested on a windows device.

**Comment by shivanmodha** [comment]
Closing this out, hasn't been a report of this since
