### ISSUE TITLE
Investigate "/r" in University

### ISSUE THREAD

**Issue by shivanmodha** [HackRU/frontend#303]
The school drop-down has a "\r" at the end that is being stored in the lcs database.

**Comment by mjrb** [comment]
from what ryan said once i think this is an issue in the list of universities in the frontend code. there is a text file somewhere in the code base i think, and we can fix this using the `sed` program

**Comment by shivanmodha** [comment]
@zain08816 We did an audit with this one right?

**Comment by zain08816** [comment]
> @zain08816 We did an audit with this one right?

Yup, should be solved now
