### ISSUE TITLE
Home Page Redesign: FAQs

### ISSUE THREAD

**Issue by shivanmodha** [HackRU/frontend#330]

**Comment by benlambert43** [comment]
https://github.com/HackRU/frontend/tree/homepageredesign330

**Comment by benlambert43** [comment]
![image](https://user-images.githubusercontent.com/46206905/88468600-46bcf080-cea3-11ea-909f-8f077d36d51d.png)

**Comment by benlambert43** [comment]
font-awesome chevrons removed, replaced with material-ui keyboard up down icons. Also, rewrote the FAQsCollapse to use functions/hooks.
