### ISSUE TITLE
Cosmetic changes discovered in walkthrough

### ISSUE THREAD

**Issue by ryanisaacg** [HackRU/frontend#35]
- [x] Too much whitespace on landing: increase font / asset sizes?
- [x] Duplicate 2018 copy on HackRU Fall 2018 / October 6, 7th 2018
- [x] Pad out Saturday to make the schedules even
- [x] If you hover the purple links, they turn yellow, which is unreadable on white <-- fixed to dark purple
- [x] MLH banner should be black on the sponsorship page
- [x] "Go to Dashboard" should read "Go To Registration"
- [x] Move Login box above the other boxes
- [x] Get rid of announcement / upcoming until day-of
- [x] Get rid of "Want to Mentor" because it's not ready yet (VHX isn't ready) <-- same thing with volunteers
- [x] Fix the date on the info panel (April 22nd -> October 6th)
- [x] Hover rules on the sidebar on the left (shouldn't turn yellow)
- [x] "GITHUB" should read "GITHUB USERNAME"
- [x] Remove livestream until day-of
- [x] Add optional ethnicity dropdown
- [ ] Change the wording of "waitlist" to be more clear to users <--- wait listed is pretty much the most concise form of this...I'm not sure what to do here, because putting `registered`, `rejected`, and `waitlisted` all under `pending` would kinda obfuscate things.
- [ ] Link snapchat in socials (maybe?) <--- did they get back to us?
- [x] Mentor and volunteer links should not be on site when it's thin
- [ ] On mobile site the links and the header look wrong <-- hamburger menu was suggested I think

**Comment by hemangandhi** [comment]
Small stuff from finance:

- [ ] Colors on the packages are not all showing up - gold is yellow.
- [ ] Add info about buses, snacks, and other alternative sponsorship means. (Wording will be here soon.)

To pad out Saturday, we can add the keynote at 12:30 PM and team building at 1 PM on Saturday.

**Comment by hemangandhi** [comment]
From finance: just a little note saying " *for alternative perks (snacks/meals/buses), please email us for details" should suffice. Up to you where you want to put it really, wherever you feel like can fit it. Also can you move the text "If you'd prefer a customized package, send us an email at sponsorship@hackru.org and we'll chat from there!" a little lower? Feel like it's too close to the last item on the package table

**Comment by hemangandhi** [comment]
Food notes: Saturday lunch is at noon and the dinner is at 6.

**Comment by TresTres** [comment]
Attempted to fix several issues in this today.  See #37 addressing #36

**Comment by TresTres** [comment]
Also disputing github vs github username but I'll add it as well

**Comment by TresTres** [comment]
0d8832d932d397fa4a472b27d4c211a57b5c085a should take care of most of this

**Comment by thekabistro** [comment]
Can we close this out and move whatever remains to the #41 ?

**Comment by TresTres** [comment]
Yes, good idea
