### ISSUE TITLE
Visual Enhancements and Tweaks 

### ISSUE THREAD

**Issue by TresTres** [HackRU/frontend#41]
- [x] Move all CSS colors to use color variables and not be hard coded 
- [x] Prevent titles from cutting off
- [x] For margin requests, use bootstrap classes instead of doing this by hand in custom css
- [x] Fix issue with font squishing
- [x] Fix issue with fb share metadata
- [x] Colliding text on mobile phones in the __About Us__ section.
- [x] Fix Google Maps link pointing to RAC
- [x] Instead of tiling background image, make it one single pane
- [x] Add explicit scroll bars to things that can scroll
- [ ] In flash "Application has been saved" over "changes have been saved"
- [ ] "Your Info" should be "Your Application"
- [ ] "Pending" should be "Pending Review"
- [ ] "Save Changes to Application" and notify user of editable submission, instead of just a simple "save", per #47 
- [x] Fix Password overlaps on iPad, per #46 
- [ ] Sponsorship Custom Package goes long off the page!
- [ ] Inconsistencies with flash messages.  If I press save changes, I get a message saying thanks for registering but when I logout it says I have not filled in the required fields.

**Comment by TresTres** [comment]
Please see https://github.com/HackRU/frontend/pull/42

**Comment by thekabistro** [comment]
I don't think this was fully fixed...It should be fine now with some bootstrap class changes #44

**Comment by TresTres** [comment]
No it wasn't on purpose, there may be other issues that may come up

**Comment by thekabistro** [comment]
Fixed the RAC link see #44

**Comment by thekabistro** [comment]
Fixed the colors on the MLH checkboxes

**Comment by dhruvilp** [comment]
(Fix Password overlaps on iPad) ---> Column size from (.col-md-8) to (.col-lg) and done! @TresTres

**Comment by thekabistro** [comment]
A number of these issues have been resolved with the css-unjumble,  see #51

**Comment by TresTres** [comment]
This issue list is going to be __deprecated__ as the dashboard CSS will be based off of #51.

Please refer to http://hackru-frontend.s3-website-us-west-2.amazonaws.com/dashboard.html from now on, as this will be a closer reflection of the updated site.  

Also, we will no longer consolidate issues into a single list, so that we can spend more time effectively communicating on each issue.
