### ISSUE TITLE
Travel Reimbursement Placeholder Text

### ISSUE THREAD

**Issue by QasimAbbas** [HackRU/frontend#54]
After the placeholder text that is already there would you be able to add placeholder text of like an example text field input so people follow a convention when entering travel?  It might help lcs out after if everything was the same format?  Right now it's very ambiguous the way the information would be entered.  Maybe separate boxes for City and State?  Right now it just seems ambiguous basically on the way the information is being inputed.

**Comment by TresTres** [comment]
Unfortunately, I'm a little confused by your ask.  My suggestion is to use an image for this issue. Could you provide a current screenshot and perhaps some markings of what you'd like to see?

**Comment by ryanisaacg** [comment]
Seconded the confusion, because the input text box has some validation on it (at least it should 😓 )

**Comment by QasimAbbas** [comment]
Oh wait, basically just get rid of "include". I see the validator.  Just to be consistent that we're only looking for City and State.  If that's all there needs to be looked for.

**Comment by hemangandhi** [comment]
I agree with Qasim. "include" is sorta weird. So like `Location of Origin (City and State)`.

(But I'm sorta weird, so no wonder it was there.)
