### ISSUE TITLE
Setting Up Global TailwindCSS colors

### ISSUE THREAD

**Issue by kevinmonisit** [HackRU/frontend#545]
<img width="550" alt="image" src="https://github.com/HackRU/frontend/assets/7038712/d5fd625c-471e-4521-852c-cf7bdb7846b2">

- Add these new colors to the tailwind CSS config so that text color can be changed with 

Look into how the text is currently colored.

**Comment by kevinmonisit** [comment]
assigned to utkarsh

**Comment by utkarshdubey** [comment]
Please have a look at https://github.com/HackRU/frontend/pull/551
