### ISSUE TITLE
Travel Forms Buttons

### ISSUE THREAD

**Issue by TresTres** [HackRU/frontend#56]
![image](https://user-images.githubusercontent.com/14167519/44708956-76281000-aa76-11e8-9af6-2899ebe3b506.png)

- [x] Please ensure that the transportation options are displayed vertically.  
- [x] Also, when traveling info is updated, we'd like to make sure the user knows that the info is saved, probably by disabling the button and setting the label to "changes saved".  
- [x] Currently, the behavior does not trigger an update to LCS.  Please change the behavior so it does, as most users won't be changing anything else once travel reimbursement is announced.
- [ ] Probably more of a CSS issue if anything, but the text field is also appearing off-center.

**Comment by ryanisaacg** [comment]
@TresTres For the second issue (the info is updated) is setting the upper flash good enough?

**Comment by TresTres** [comment]
@thekabistro still need a fix for the 4th issue

**Comment by thekabistro** [comment]
See #68
