### ISSUE TITLE
Pre-day of Changes

### ISSUE THREAD

**Issue by hemangandhi** [HackRU/frontend#80]
We need the following for day-of:
 - QRs on logged in dashboard
 - Slack announcements
 - Calendar events view
 - Map of the venue (coming soon from a logistics team near you)
 
Other note: registration will re-open on the day of. So may be have the frontend reflect that? (This isn't critical since we don't recommend registering on the day of either...)

**Comment by hemangandhi** [comment]
^ off the top of my head. Stay tuned for edits.

**Comment by TresTres** [comment]
Sponsorship logos ✔️ 
Map ❌ 
Calendar events ❓ 
Slack announcements ❓ 
QRs ❓

**Comment by TresTres** [comment]
Got the map link, I am probably going to make a big old content div that links to the map?

**Comment by TresTres** [comment]
Check out #87
